### ISSUE TITLE
默认配置建议修改

### ISSUE THREAD

**Issue by foryouos** [theme-shoka-x/hexo-theme-shokaX#123]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题

### 建议描述

1，建议默认开启darkmode功能，其适应浏览器主色调确实实用
# 是否遵守夜间模式等级
# 默认情况下，是否开启夜间模式取决于(优先级从高到低)
# * 访客点击头部自行选择
# * 浏览器设置主题色调
# * darkmode配置
```yaml
darkmode: true
```
2，建立默认关闭自动定位，从每次打开网站体验来看
```yaml
# 是否开启自动定位
auto_scroll: false
```
3，建立默认关闭文章失效
```yaml
# 文章是否失效
outime:
  enable: false  #关闭文章失效
  days: 90 # 超过 90 天文章失效
````

### 注意事项

- [X] 我已确认以上事项
