### ISSUE TITLE
shokaX 不支持在Markdown内嵌HTML标签吗

### ISSUE THREAD

**Issue by Nana7mij** [theme-shoka-x/hexo-theme-shokaX#161]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 建议描述

您好我想问下，shokaX是不支持在Markdown文档中内嵌HTML标签吗，因为我是很久之前用的shoka主题好久没更新了，那时候的shoka是支持的，感谢大大回复

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
config中
```yml
markdown: 
  render: # 渲染器设置 
    html: true # 过滤 HTML 标签
```
false👉🏻true试试
