### ISSUE TITLE
waline 请求评论链接格式问题

### ISSUE THREAD

**Issue by YangLinzhuo** [theme-shoka-x/hexo-theme-shokaX#364]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

waline 评论系统用于获取评论信息时生成的链接格式有些问题。

当前生成的链接是 `https://comments.linn-ylz.com/api/comment?type=recent&count=10&lang=zh-CN`，这个会报告 `/api/comment` 404 的错误。

我把里面的 `/api` 去掉之后，是可以正常获取到数据的。

请问这个会是什么原因呢？

我在之前的 issue 中看到了类似的 waline 获取数据的问题，但是里面说已经修复了，不确定是不是同样的问题。

尝试过 `git clone shokax` 到 `themes` 目录下以及ShokaX 即食罐头两种，好像都是一样的问题。

yaml 里面配置在下面，这个是直接从我之前的配置复制的，不知道是否有问题：

```yaml
waline:
  enable: true
  serverURL: https://comments.linn-ylz.com    # 填入刚刚得到的后端 URL（必填）
  visitor: true   # 文章访问量统计
  lang: zh-CN     # 语言，默认 zh-CN
  login: enable   # 登录模式状态，默认值 enable，force 可以强制登录
  wordLimit: 0    # 评论字数限制，0 为不限制，默认值为 0
  pageSize: 10    # 评论列表分页，数字为条数，默认值 10
  highlight: true # 代码高亮，默认 true
  meta: ['nick', 'mail', 'link'] # 评论者相关属性，默认 ['nick', 'mail', 'link']
  requiredMeta: ['nick', 'mail'] #设置评论者属性必填项，默认 []（即匿名）
  placeholder: '( •̀ ω •́ )' # 评论框占位提示符，默认 ' 欢迎评论'
  copyright: true # 是否显示页脚版权信息
  pageview: true # 浏览量统计
  emoji: # 表情包，默认为 waline 官方配置
    - https://unpkg.com/@waline/emojis@1.0.1/weibo
    - https://unpkg.com/@waline/emojis@1.0.1/alus
    - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    - https://unpkg.com/@waline/emojis@1.0.1/qq
    - https://unpkg.com/@waline/emojis@1.0.1/tieba
    - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
```

### 相关配置

- hexo 7.3.0
- waline 3.3.2

### 注意事项

- [X] 我已确认以上事项
