### ISSUE TITLE
目前封面图片无法显示的临时解决方案

### ISSUE THREAD

**Issue by zkz098** [theme-shoka-x/hexo-theme-shokaX#6]
目前新浪图床开启了防盗链,所以所有cover图片都无法正常加载,解决方法如下:
- 自托管封面图片
- 使用CSS渐变模式

### 自托管
[点我](https://gitee.com/zkz0/image/tree/master)跳转到作者做的封面图片备份,将备份clone到本地或服务器上,剩下的和静态网站托管一样
修改`_images.yml`内的内容,参考此格式:
```yaml
- http://example.com/img1.webp
- http://example.com/img2.webp
# ...
```

### 使用CSS渐变模式
此模式将文章封面修改为CSS渐变来解决此问题
修改主题`_config.yml`
```yaml
experiments:
  gradient: true # 使用CSS渐变作为文章封面
  fixedCover: "/cover.webp" # 当gradient为true时使用的主页面cover或者主界面的固定Cover(0.1.5+)
  # 上面的配置请设置为自己的背景图片
```
随后重新`hexo g`即可
