### ISSUE TITLE
音乐播放器无法加载

### ISSUE THREAD

**Issue by CLanNT** [theme-shoka-x/hexo-theme-shokaX#79]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

音乐播放器不能正确加载，打开网页没有任何操作控制台就弹出报错
![QQ图片20230430123107](https://user-images.githubusercontent.com/74392382/235335591-590b037e-2d84-4b83-bf69-a06a87dc9921.png)
![image](https://user-images.githubusercontent.com/74392382/235335617-98e39356-275b-4c5d-81b2-f1d673a53552.png)

### 相关配置

node版本 v20.0.0
hexo版本 6.3.0
shokaX版本 0.2.4

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
是不是配置有点问题？
请确保audio配置有如下格式
```yaml
audio:
  - title: 列表1
    list:
    - https://music.163.com/#/playlist?id=2265921590
```
如果又出现了以下错误
![image](https://user-images.githubusercontent.com/49871906/235345214-65a57c66-86e8-4509-8a06-c8cead7faf75.png)
#80 已经修复
